### ISSUE TITLE
How can I insert IPFS CID here?

### ISSUE THREAD

**Issue by DevTGAI** [thirdweb-dev/thirdweb-cli#13]

**Comment by DevTGAI** [comment]
I would like to know that instead of uploading media files to Third Web, I like to upload them on IPFS myself and pinned it through Pinata. Now, I want to know how can I insert the IPFS CID value.

**Comment by jnsdls** [comment]
Hi @DevTGAI I am unsure how this is relevant to the thirdweb CLI? The CLI is used to compile and deploy smart contracts, not upload media files to IPFS. Please feel free to elaborate on the problem you're trying to solve and we'd be happy to help.

**Comment by DevTGAI** [comment]
@jnsdls  I want to know where can I can update my IFPS {CID} in the third web smart contract.

**Comment by jarrodwatts** [comment]
Hey @DevTGAI you can do this using our Web3 SDK but not as part of our CLI. Here's how:
https://portal.thirdweb.com/web3-sdk/advanced-features/custom-storage
